draw_dragon :-
    write('yo`                                                                                                 '),nl,
    write('/dms.                                    `+o-                                                       '),nl,
    write(' smdNds/-`     `.-:/+osyyhhhyyso+/-`       -hNy/.         `                                         '),nl,
    write('  oNhhmMMNNNmNNNNMMMMMMMMMMMMMMMMMMNmy+-     -hMNd+-      +s.                                       '),nl,
    write('   :dNmhhhmNMMMMMMMMMNNmmmmmmNMMMMMMMMMNmo-    :dMMNdo-    +No`                                     '),nl,
    write('    `:hNNNmhyyyyysssyyyhhhhhyyoooymMMMMMMMNd/`  .sMMMMNdo-  :Nm+`                                   '),nl,
    write('       ./ydNMMMMMMMMMMMMMMMMMMMNNh+/smMMMMMMMm+`+mMMMMMMMNdo--dMd:                                  '),nl,
    write('          `..:://+++++oosydNMMMMMMmds:/dMMMMMMMs :+oydNMMMMMNdoyMMh-   .`                           '),nl,
    write('                   `-:+yddyo+yMMMMMoods-/mMMMm//hmmmhyooymMMMMMNNMMNy- sy                           '),nl,
    write('              `-/sdmNMMMNNMMNo+MMMMN-osd/.oNd.sNMMMMMMMNmhhmMMMMMMMMMNyyM+                          '),nl,
    write('          `:ohddhdMMMMNmNMMMMMoyMMMM+mmsso.:.oMMMMMMMMMMMMMmddhyssssydNMMN:                         '),nl,
    write('        .+oo/-..oNMMhsshdmNNMMMsmMNmyMMMmy+``NMMMMMMMMMMMMMMMMMMNNmdy+/+hNN-                        '),nl,
    write('        ``    :dMMNdmNh/--+syhddhdmNMMMMMMNh+sdMMMMMMMMMMMMMMMMMMMMMMMNh/:hN:                       '),nl,
    write('             +NMMmhNMMMMms/sysydmNMMMMMMMMMMMNdydmMMMMMMMMMMMMMMMMMMMMMMMd/yNo``y`                  '),nl,
    write('           `sMMMdhMMMMMMMMNhhMNdhyydmNMMMMMMMMMMNmmNMMMMNmmddmmNNmmmNMMMMMN+MMddMy                 `'),nl,
    write('          `yMMMhhMMMMMMMMMMMdhMMMMMmddhmNNMMMMMMMMMMMMMMMNhymdhys/-`hmMMMMMNMMMMMM/               .h'),nl,
    write('         :dMMMhyMMMMMMMMMMMMNyMMMMMMMMMNmmmNMMMMMMMMMMMMMMMssMMMm:`-/.ohhhdNMMMMMMN-             `dm'),nl,
    write('       `sMMMMmoMMMMMMMMMNNmhdNMMMMMMMMMMMMMMNNNMMMMMMMMMMMMd.MNNNMdysydmdyNNMMMMMMMN:           .dMs'),nl,
    write('      :mNMMMN/mNmmdhyssyhhdNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMo/MNmdhhhhhssomMmdNMMMMMMMs.``/s    .dMM:'),nl,
    write('     oNh+MMNy/s+:...:osyyyyyyyyyyyhhhhhdddmmNMMMMMMMMMMMMNs:NMMMMMNNy++hMMMMNhhNMMMMMMNhdMs   :NMMm '),nl,
    write('   `ym/ +MMModMMMMNmdyssdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhshMMMMMNmmdmMMMMMMMMMNhshNMMMMMMM: `sMMMMo '),nl,
    write('  `hy.  yMMM/NMMMMMMMMMMhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMNmNMMMMMMMMNhmNMMMMMMMMMMMMdsohNMMMMdymMMMMN` '),nl,
    write('  //    yMMM/NMMMMMMMMMMMMsMMMMMMMMMMMMMMMMNNNMMMMMNmdysoo+++sNMMMMhsoshmNMMMMMMMMMMh+sNMMMMMMMMM+  '),nl,
    write('        yMMM+dMMMMMMMMMMMMsMMMMMMMMMNmhhdmmMMMMMMNmddmmmmdhyo:./ymMMMMNdyyhhhddmNNMMMMs-s+dNdoNMd   '),nl,
    write('        yMMMyoMMMMMMMMMMMdyMMMMNdyyyhmMMMMMMMMMMMMMMNddmMMMMMMNy- `:+MNhNMMMMMMMMMMMMMM-`NMMNyhMy   '),nl,
    write('       -MMMMN.NMMMMMMMMMhoMNyssymMMMMMMMMMMMMMMMds/:+ydmMMMMMMMMMy. .: .dy:`dMmosMMMMMMm`hMMNyMMh   '),nl,
    write('       mMNMMM+oMMMMMMMMo:+-.+ssyyhhNMMMMMMMMNyoshm       ./smMMMMMMs`..    oh/  :MNo:dMMm+oNMMMMy   '),nl,
    write('      +M+oMMMN.dMMMMMy::ohmmmMMMMMMsmMMMMms+smMMMMo          .omMMMMMN.   `    `s/` `NNodMNoyMMM+   '),nl,
    write('      Nh `NMMMh.NMNmhmMMMMMMoMMMMMMhyMNy/odMMMMMMMMy`          `/mMMMMmoyd`         oo. mmyMdsMM.   '),nl,
    write('     :N.  +MMMMs-NMMMMMMMMMMdsMMMMN/mo:sNMMMMMMMMMMMm/           `+NMMMMMo`./y`        :/`oNMsMy    '),nl,
    write('     s/    yMMMMo:NMMMMMMMMMMysMMN///hNMMMMMMMMMMMMMNm.            .hMMMMMNNm- -so  .:   ./.shd`    '),nl,
    write('     -     `dMMMMo:NMMMMMMMMMMyod-/dMMMMMMMMMMMMmdddNMy.            `hMMMMMMMmmNN//ym/--.   `o.     '),nl,
    write('            `dMMMMo-mMMMMMMMMMM+.:oyyhhhhhyyyysydNNMMMMNs.           shhMMMMMMMMMMMMMds:`           '),nl,
    write('             :MMMMMy-dMMMMMMMNhmm/:ssssyyhdmNNMMMMMMMMMMMNs-         -omMMMMMMMNmdy+-`              '),nl,
    write('              mMMMMMh.yMMMMMMNMMMNy+hMMMMMMMMMMMMMMMMMMMMMMNh:`      `..--:::-..``                  '),nl,
    write('              oMdNMMMd-oMMMMMMMMMMMNs/hMMMMMMMMMMMMMMMMMMMMMMMmo-                                   '),nl,
    write('              .Ms-dMMMm-+NMMMMMMMMMMMmo/yNMMMMMMMMMMMMMMMMMMMMMMNd+                                 '),nl,
    write('               my .hMMMm-/NMMMMMMMMMMMMm+:yNMMMMMMMMMMMMMMMMMMMMNN:                                 '),nl,
    write('               sh  `hMMMm./MMMMMMMMMMMMMMm+:yNMMMMMMMMMMMMMMMmddNMm:                                '),nl,
    write('               -y   .NMMMy yMMMMMMMMMMMMMMMd::dMMMMMMMMNmdhysdNMMMMNo                               '),nl,
    write('                .    oMMMM..MMMMMMMMMMMMMMMMNs.+oooo++++oydNMMMMMMMMMs                              '),nl,
    write('                     /MMMM+ mMMMMMMMMMMMMMMMMMh``syhdmNMMMMMMMMMMMMMMMs                             '),nl,
    write('                     yMMMMo hMMMMMMMMMMMMMMMMMMd`/NMMMMMMMMMMMMMMMMMMMM/                            '),nl,
    write('                    oMMMMM/ dMMMMMMMMMMMMMMMMMMMy +MMMMMMMMMMMMMMMMMMMMN.                           '),nl,
    write('                    :hNMMm``NMMMMMMMMMMMMMMMMMMMM: hMMMMMMMMMMMMMMMMMNms.                           '),nl,
    write('                      .+y- +MMMMMMMMMMMMMMMMMMMMMd .MMMMMMMMMMMMMNmy+-                              '),nl,
    write('                           /ymNNMMMMMMMMMMMMMMMMMM. hMMMMMNNmhs+:.                                  '),nl.

draw_slime :-
    write('                                     `-/+ossssso+/:.                               '),nl,         
    write('                                 `:sdmdhyso+++oshdmNmh+-`                          '),nl,         
    write('                               `+dNd+-``         `.-+ydNms-                        '),nl,         
    write('                              .hMN+`                  `-odNh:                      '),nl,         
    write('                              hMN- :o.    `..---.`       `:hNs`                    '),nl,         
    write('                             :MM/  h/  ./sysssyyhhyo-      `oMd.                   '),nl,         
    write('                             yMh   .- omh:`  -:-``-yNs`      yMh                   '),nl,         
    write('                             dM+     oMy`  `ysom+  `hMs      .MM:                  '),nl,         
    write('                             NM-    `NN`   `m+/ho   /Mm       mMs                  '),nl,         
    write('                            `MM`    /My     ./:-`   +Mh       hMh                  '),nl,         
    write('                            -MN     /Ms            `dN-       sMd                  '),nl,         
    write('                            oMh     `ms           `sd-        oMm                  '),nl,         
    write('                           `mM+      -my.  .:++oosy/``/+/`    +MN                  '),nl,         
    write('                          .dMh`       -Nm/yNm+-::.   dMdNy    .MM`                 '),nl,         
    write('                         .mMy`         :sys/`        sNhdo     mM-                 '),nl,         
    write('                         :MM`                         ``       sM:                 '),nl,         
    write('                          hMs        ./+- ``-::--`             +M+                 '),nl,         
    write('                          `hMs      /y/sMhsyNd/+mNds-          :Mo                 '),nl,         
    write('                      `    `NM`     sh+dmh+s+ohyNd-hMs         -My                 '),nl,         
    write('                    `ymddh  sM-      -hM`       `+hhhd         `Md                 '),nl,         
    write('                    oMh+mMo :M-       .shh-   `/+/` /N          mN`                '),nl,         
    write('                    -hmdy/  -M-         .dN/-oy+-od`:M`         sM/                '),nl,         
    write('                            -M.         `hMdys:   hyoM`         .Mm                '),nl,         
    write('                            +N   s` .:    ./++`   -dh/           +Mo               '),nl,         
    write('                           `dh   h: hs    .oo.     ``             yM-              '),nl,         
    write('                           oN/   :hy+`     ``        /ssdo        `md              '),nl,         
    write('                          -Mm     ``                `msoh/         sM:             '),nl,         
    write('                          sMo              `         ...`         `yM:             '),nl,         
    write('                          sM-            -yhd+                 +dhmNy`   :oo-      '),nl,         
    write('                          -Nd`           sy:om                 yMd/.    od:+N      '),nl,         
    write('               .:-`        oMh   ..      ./++-       ..        sMh      hy+yo      '),nl,         
    write('              odyNy        `mM:  s+.`               sss/       :Md      .::.       '),nl,         
    write('             `mmdd:         +Ms  `++`               :so.        mN`                '),nl,         
    write('              .:-`       `..+Md``                               :Mh:-----.`        '),nl,         
    write('                    .:+syyhddhy+/`                          -osssddhhhhhdddho-     '),nl,         
    write('     :osyys+.     `smdo:.``                                  ```         `-/hNs    '),nl,         
    write('     :My/:/oNm`    :MN:...-:/+syhhhhs+-`      `.`````                `````.-/yMM:  '),nl,          
    write('     -mysssys:     `ohdddddhyyso++++ohmdyo//oyddhyhhhyyyyyyyyyyyyyyyhhhddmNNNNmy`  '),nl,          
    write('     `                             `:+sso+:-...-:/+osssssssoo++//////::::--`       '),nl.
draw_wolf :-
    write('                                   ommy`                                                             '),nl,
    write('                                 `./.-o:                                                             '),nl,
    write('                                 -oy.``:+.                                                           '),nl,
    write('                                 .`.+:``.+-                                                          '),nl,
    write('                                 .```..```:/:.                                                       '),nl,
    write('                                  .`````````:+o:                                                     '),nl,
    write('                                  ..`````````:/so`                                                   '),nl,
    write('                                  .``````````-/sso                                                   '),nl,
    write('                                 `.`````````:oooss:                                                  '),nl,
    write('                                 ..`````````-/oooso-`                                                '),nl,
    write('                                 ...````````.-+oooooo:                                               '),nl,
    write('                                  .-````.`...-:ooooooo-                                              '),nl,
    write('                                  .`````.--/++oos+//+oo`                                             '),nl,
    write('                                `.````````-:ssooosssoos+`                                            '),nl,
    write('                                ``````````.-/oooosssys:-`                                            '),nl,
    write('                               `.````````.--:soooossyo:`                                             '),nl,
    write('                                .````````--++sooooooss:`                                             '),nl,
    write('                               `.```````..:+ssooooooosy+`                                            '),nl,
    write('                                --`````.--ssoooooooooosys/`                                          '),nl,
    write('                                 :-`..`-+/soooooooooooossss:                                         '),nl,
    write('                                 ------:+oooooooooooooooossso-                                       '),nl,
    write('                                  .--::-`/ooooooooooooooooossso-                                     '),nl,
    write('                                   .-:-.``-ooooooooooooooooooossso:.                                 '),nl,
    write('                                    `.-.```-ooooooooooooooooooooossss/`                              '),nl,
    write('                                       :-.``/oooooooooooooooooooooossss/                             '),nl,
    write('                                       -o+:..ooooooo+/ooooooooooooooossso`                           '),nl,
    write('                                       +osso::oooo+-`-//+++ooooooooooosss/                           '),nl,
    write('                                      :ooossssoo+-``.-.````:oooooooooossss                           '),nl,
    write('                                     .o+:-:::oo/````-:-----/ooooooooooossy:`                         '),nl,
    write('                                    `+-```--/o-````---------ooooooooooossyoo-                        '),nl,
    write('                                   `/````--`+-```.--` `++/::/ooooooooosssyooo+`                      '),nl,
    write('                                   -````--`.:```.--`   .-+ssssoooooooosssyooooo:`                    '),nl,
    write('                                  .```.--  -```---`     .`./oso:/ooooosssyooooooo/.                  '),nl,
    write('                                  .``.--   .``.--`      ````-+so```.:+sssysooooooooo/-.              '),nl,
    write('                                 ````--   ````--.        ````/s/`.````:osysooooooooo/:::-`````   ``` '),nl,
    write('                              ```.``.--   .```--          .``/s`  ````.-/syssooooooooo/-````.``.-.`` '),nl,
    write('                       ..-::-.:.`.``--.  ````.-.          .``:s`    ```.-/yyssssoooooo++/:-``.--.    '),nl,
    write('                   ``.:://////+:::-:/+:.`````--`        `.```-s`     ````-+yssssosss+//:-.``.--.     '),nl,
    write('               `-://////++++///+++++/+-.`-``.-:.   ````.````-:`       .``.:+`./o/-:///-::--::.       '),nl,
    write('             `-:///////+++++++ooo+++/++--:--:++///:/-..````-.         .``.:.    .. `.:-.-.`          '),nl,
    write('       ``  .::/++++/////:::::::::::////++++++///++oso//-..-`         ````.-           .              '),nl,
    write('    `-/////:/+/////////////////////++++oooooooooo++/////+/:`       ``````.:                          '),nl,
    write('    :///++////+ooo+++++++++++++///++++///:::::::::::///////++/-.``.-.`.``.-.                         '),nl,
    write(' .://++o+//+++++/+++++++++++oooosooo++++++//////++////////+///////++::/:::/..``                      '),nl,
    write('+sooooosss++////++++/////////////+++++++++++++++////////::://///////+++++++++++oo+:-                 '),nl,
    write('.-::--/osssssooo++++++++++/////+o+////////+++o++++++++ooo+++++//////++++oo/////+ossso/:.             '),nl,
    write('        `..-----::::://+++++++++//+ooooooo+/++++//::----::///+++++////+ooooooooooo++++//.            '),nl.
draw_goblin :-
    write('                                      .            `-::-.                       '),nl,                    
    write('                             //-   .:/:::/oo/::/+sso::-`                        '),nl,            
    write('                             /+o .+-```.`      .---:/..//::-.                   '),nl,            
    write('                             :s/o++/ss/+-:/+/:-.```.-:: ``..://:`               '),nl,            
    write('                             `hd. ` `-+.-s/:+/sso+/:-+: --   ``-++`             '),nl,            
    write('      ```                     :Noso/-/o/+:     ``.```oh:    .:-+ :s..------.    '),nl,            
    write('    `.``  `                  `/s:moohdm-sdyssooosho/``-y`  `-.so//o+/:/-.://    '),nl,            
    write('  `..`..                     o-..+/oy+.``/ysy/s++ds+/:`:s   -//syss/.+///-`     '),nl,            
    write(' ..-//:::-                   s.``-+o:```  .+s-/:+s+. :--s   s/dh::../+/         '),nl,            
    write(' --s:`` .+                   .o/hNo`   .-//-dy-``    `:y.  `s-h+.`./o           '),nl,            
    write(' .oNho++y`                    s:-h`./oshdsshsydysso.`hN/ ` -s-o/-:+y            '),nl,            
    write('  `/so+s/                     :/`-/odhmmNhmyyoy+//o/:Mh  s .Mmms-.:+            '),nl,            
    write('                               s/ ::++//++os/-.  ```os. :M:`MMMm:`o:            '),nl,            
    write('                               omy-.o+oshs/- ``.:+ss- `+mmy+hmNMy/.s.           '),nl,            
    write('                               symd.`` ```./shmNMNd``/hs-     .+mNs-y.          '),nl,            
    write('                               ooy.////s+ymNNNmhoy:smN/`  .     /MMh/++`        '),nl,            
    write('                               so//-``o/mMm/.NdhohoNsN-.-.`    `yMNMm`.y        '),nl,            
    write('        -`                   -oy-hhhyhymNh`. :N/:ymy`odo--:```/dMM-yMo y`       '),nl,            
    write('      ` ++/`...            .so+ddmhy+ss+:y --`y yd.yy:`:oydhmNMMNm- hN.h        '),nl,            
    write('     /+:ss+o/.:oo+///::-. /soyomssossyy+h-   `y  ` -NMNho/--:////s: `oy/        '),nl,            
    write(' ::o/s.s+/y/yNMMmhosoyoys/::ssMM+o.     `m/   h     .mohNMMMMMNd+o              '),nl,            
    write('  +ososmmdy+:.`-/oydNMNNms+.+NNdy+ -..  :shhyymhyyyhymssyMMMoyhd+s              '),nl,            
    write('   -+os/`            `-/oshmy/syyy::///+mMMMNmmdy+/+yo`-oNM+ohmo//              '),nl,            
    write('                               +MMMMs+++hyhdNMMMMMMmNs -NMdshmMmh-              '),nl,            
    write('                              omNmMM.   -hmMMMMMMMMMMMhdNNmNmyysh+              '),nl,            
    write('                            .s+m+smm    /y-+MdmddmmmmdNMNNNMhsd:.o-             '),nl,            
    write('                           -soN++/+y    hs` /o:yMMMMMMMNdhh///.-:-+/            '),nl,            
    write('                          /+sMs:.+-s  .:s:s``::/:/syysooy+.o-    `-y/           '),nl,            
    write('                        `o:oNh./.-.s:/:`  +y .oyoo/+oyhs.`s.       :m           '),nl,            
    write('                       :o-/ym././ `d.     .M: `/mhyhdys` yh         o-          '),nl,            
    write('                     .o: .:d-`::-. h    `.sMd-//:oNh:+  /MN+`       `y          '),nl,            
    write('                   `//`   y/ `-- / h     .mMNsosh//-.oo-NMMMh:`      +:         '),nl,            
    write('                 `/+--`  /o   :  / h  ` .dms-+dhydNd:-.mMMMmhh:      `y         '),nl,            
    write('               `:+/:-.::ss`   .  : y.o- hMo  `dNhhMmh+/+yN+o`:do .    s`        '),nl,            
    write('             ./++++++s++h`       ` +/:`.mMh  `+soo:y+/+``-    sm`s+`  -/        '),nl,            
    write('            :+-oy+os:hy+`          -y/+/yMm:       `.``       :M-:/+-//y.       '),nl,            
    write('            o::myodmys/            `y :dMd.`                  -mdd/:. -+        '),nl,            
    write('         `.-+yoo+yyo/---            h.:hNh`                    .sM+`  s.        '),nl,            
    write('      .//::.` +oyhhhso:             oNm:yM:                     odho+/d         '),nl,            
    write('    -+:`         `..         `   .` +MM+:my                     +:NMmo+         '),nl,            
    write('   /+  `-                 ``-:   :``mMMN:.Nhyyyysoo+/:--..``````/smMNm-         '),nl,            
    write('  :+   `:     -` .-`      .+o-   ` sMMMMo+NMMMMMMMMMMMMMMMNNmmmmdoMhsds/-`      '),nl,            
    write('  h`  :.  -/ .     `     `:/- `osyhMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy/Mm:omd::+:`   '),nl,            
    write('  h:`/.:`:/d:+`:..o+`   -:hs: `/MMMMMMMNNNNMMMMMMMMMMMMMMNMMMMMN:/ms`/sm/:.yy`  '),nl,            
    write('  :mdhddoyMNNMmNMyhMmso+oshshyhNMMMMNh/`` `:/oyhdmmmdhyo/.-/oyyds/s/o:+o+.:--`  '),nl,            
    write('    -+osyyyhhhhhddmmmNNNNNmmdyssyso:`                          `+.   `:/        '),nl.
draw_skull :-
    write('        ````     ````    ````    ``````.:+oyhddmNMMNmmdhyss+//.``  ````    ````    ````    `````    '),nl,
    write('    ````     ````    ````    ./oymNMMMMMMMMMMMMMMMMMMMMMMMMMNmdyso/-.` ````    ````    `````    ````'),nl,
    write('````    ````     ````    ./sdNMMMMNmdyso+//::---::://+osyhdmNMMMMMMMMNdyo/-.```    `````    ````    '),nl,
    write('````    `````    ```` .+hNMMMNhs/-``                       ``.-/oshdNMMMMMMNmyo-`  ````     ````    '),nl,
    write('    ````    `````  `:yNMMMdo-`                                     ``.:+symNMMMMmy/`   `````    ````'),nl,
    write('    ````    ``````+dMMMmo.`                                              ``.-+shNMMNy/``````    ````'),nl,
    write('````     ````   /dMMNh:`                                                  ``````.:ohNMmo.`  ````    '),nl,
    write('````    ````` .hNMMh:`                                                    ``````````.+dMNy- ````    '),nl,
    write('    `````   `/mMMm/`                                                      `````````````:yNNy- ``````'),nl,
    write('    ````    oNMMy.                                                        ```````````````:dMNs` ````'),nl,
    write('```` `   ``sNMMo`                                                        `````````````````.yMMd:`   '),nl,
    write('````    ``oNMN/                                                         ````````````````````oNMN/   '),nl,
    write('````     /NMN:                                                        ```````````````````````/NMN/``'),nl,
    write('    ````.mMN/                                                        `````````````````````````:mMN-`'),nl,
    write('    ````oMMs                                                       ````````````````````````````/NMd`'),nl,
    write('````   .mMm.                                                      ``````````````````````````````hMM/'),nl,
    write('````   +MMo                                                     ````````````````````````````````oMMy'),nl,
    write('    ```hMN.                                                    `````````````````````````````````oMMm'),nl,
    write('    ``-NMs`                                                   ``````````````````````````````````oMMM'),nl,
    write('```` `hMN-                                                   ```````````````````````````````````sMMN'),nl,
    write('````-yMNo`                                                   ```````````````````````````````````mMMh'),nl,
    write('  `yNMNo`                                                    ``````````````````````````````````-NMMs'),nl,
    write(' `hMMm/`  `....`                 `.:/+oo++/-.`               ``````````````````````````````````oMMM:'),nl,
    write('`oMMN/`-+hmmNmmdho:.          `.+hmNMMMMMMMNmdy+:.           ``````````````````````````````````dMMm`'),nl,
    write('.NMMo`omMMMMMMMMMMNdo-`      `smMMMMMMMMMMMMMMMMNmho:.       `````````````````````````````````/MMMs '),nl,
    write('oMMm.sMMMMMMMMMMMMMMMN+`     -MMMMMMMMMMMMMMMMMMMMMMNmy+-`   `````````````````````````````````hMMM-`'),nl,
    write('dMMy-NMMMMMMMMMMMMMMMMm.     `yMMMMMMMMMMMMMMMMMMMMMMMMMNh/` ````````````````````````````````:NMMy``'),nl,
    write('NMM/+MMMMMMMMMMMMMMMMMh`      `dMMMMMMMMMMMMMMMMMMMMMMMMMMNd:  ``````````````````````````````yMMN:  '),nl,
    write('mMN.oMMMMMMMMMMMMMMMMN:        .dMMMMMMMMMMMMMMMMMMMMMMMMMMMNo`   ``````````````````````````:NMMh`  '),nl,
    write('yMN`oMMMMMMMMMMMMMMMN/`         -mMMMMMMMMMMMMMMMMMMMMMMMMMMMM/    `````````````````````````hMMM:```'),nl,
    write(':MN--NMMMMMMMMMMMMMh:`           :mMMMMMMMMMMMMMMMMMMMMMMMMMMMo    ````````````````````````/MMMy````'),nl,
    write('`hMy`/dNMMMMMMMMNh/` `..`         :NMMMMMMMMMMMMMMMMMMMMMMMMMN:    ```````````````````````.mMMN-    '),nl,
    write('`-NN: `-+hmmmdy+-`  .ymNds-        :mMMMMMMMMMMMMMMMMMMMMMMMMy`    ```````````````````````sMMMo`    '),nl,
    write('  oMd.   ``.``     .dMMMMMm+`       -dMMMMMMMMMMMMMMMMMMMMMMh.     ``````````````````````/NMMh. ````'),nl,
    write('  .NMo            `hMMMMMMMMy.       `+dNMMMMMMMMMMMMMMMMMmo`     `````````````.:-``````:NMMd.  ````'),nl,
    write(' ``mMm`           :MMMMMMMMMMd.        `-:+osyhddmmmmmmdy+.   ``````````````./ymMh````.+NMMh-`` ````'),nl,
    write('``.NMm`           +MMMMMMMMMMMd.               ```....``  ` ``````````````-odMMNh-`.:smMMmo`````    '),nl,
    write('``.NMd            /MMMMMMMMMMMMh`                     `````````...``````.omMMNh+-/sdMMNdo-``````    '),nl,
    write('  `hMm/-.``       .dMMMMMMMMMMMN-              `````````````.+hmmdhs-``:dMMNdsohmMMNmy:`````    ````'),nl,
    write('   :mMMNmdhyo+-    -ymmhsoosyyy+`            ``````````````/dMMMNNmd+`oNMMMNmMMMNms:.   ````    ````'),nl,
    write('````./oshNMMMM/      ```                     ````````````-yNMMms/..`.yMMMMMMMNms:` ````     ````    '),nl,
    write('````    `+MMMy`                              ``````````.+mMMNs-`````yMMMMMMmy:`    ````    `````    '),nl,
    write('    ```` .NMM/                                 ```````:hMMMd:``````oMMMMMd+.   ````    ````     ````'),nl,
    write('    ```` `mMM+                                  ````-sNMMmo```````:NMMMm/``    ````    `````    ````'),nl,
    write('````    ``dMMh` `:/` `:+-  `.`    ``    ``  `/so``-sNMMmo.````````hMMMh.   ````    ````     ````    '),nl,
    write('````    ``oMMMo`oMM/ /NMd` sNm+  +md/  odh- -MMMyhNMNdo.`````````/MMMh`    ````    ````     ````    '),nl,
    write('    ````  `NMMMyNMMy+mMMd./MMMm.`hMMm.-NMMd:sMMMMMms:.```````````dMMm. ````    ````     ````    ````'),nl,
    write('    ````   mMMMNMMMMMMMMNmMMMMMNdMMMMmNMMMMMMMMMm+.`````````````/MMMo  ````    ````    `````    ````'),nl,
    write('````    ``:NMM++MMmodMMMMmNMMMMNNMMMMNNMMMMhdMMM/``````````````.dMMm.``    ````    ````     ````    '),nl,
    write('````    ``sMMm +MM+ -NMMs`-MMMm::mMMM/.hMMM.`sNm:``````````````sMMN/```    ````    ````     ````    '),nl,
    write('    ````  yMMd :do` .mNd. `dMMo  sMMN. -mNd```-.`````````````.sMMN/    ````    ````    `````    ````'),nl,
    write('    ````  oMMN`      .-`   .++`  `+s:   `.`````````````````.omMMd:`    ````    ````    `````    ````'),nl,
    write('````    ``:NMM:                          ```````````````.+hNMMd/`  ````    ````    ````     ````    '),nl,
    write('````    ```dMMd`                         ```````````./sdMMMmy:`    ````    ````    ````     ````    '),nl,
    write('    ````   -NMMy`                       ````````.:ohNMMMmy/`   ````    ````    ````    `````    ````'),nl,
    write('    ````    :NMMd/.                    `````.:ohmMMMNdo:``    `````    ````    ````     ````    ````'),nl,
    write('````    ```` .sdNMNdyo/:-.``         ``.:+sdNMMMMNh+-`    ````    `````    ````    ````    `````    '),nl,
    write('````    ````    .odNMMMMMMNNNmdhhhhddmNMMMMMNmy+-`````    `````    ````    ````    ````     ````    '),nl,
    write('     ```  ` `````  `-/+syhdmmNMMMMNmmddys+/-` ```     ````     ````    ````     ```    ````     ````'),nl.

draw_win :-
    write('    ```                                                                ```                     '),nl,     
    write('...                                                                `.`                         '),nl, 
    write('                                                                                               '),nl, 
    write('         ``     `                                                   `/oys+:-`                  '),nl, 
    write('      ...`.-.-..` `..                     `-                       /NMMMMMMMmho/.              '),nl, 
    write('     `...`.-::-:----`               ./oyhhhmd-                   .sMMMMMMMs.  ```              '),nl, 
    write('           .--..                 `:hMMMMMMMMMMo`              /ymMMMMMMMM+    `..              '),nl, 
    write('          `     `                   `./yMMMMMMMNy+/           -MMMMMMMMmd`                     '),nl, 
    write('                                        .dNNMMMMMMd.          :MMMMMM+`                        '),nl, 
    write('                                            `/NMMMMM/        :NMMMMMy                          '),nl, 
    write('```                    ``                    `:smMMMM/     omMMMMMNh/                          '),nl, 
    write('..`                   `..                    ..` oMMMN.   oMMMMMM+`                            '),nl, 
    write('                                                `::--yM+/dN+::/hs                              '),nl, 
    write('                                                ```-smMMMMMd+` `-                              '),nl, 
    write('                                               ohoyMMMMMMMMMMNs.                               '),nl, 
    write('                                             -yMMMMmsoMMMMMMMMMMmy-           ```              '),nl, 
    write('                                           omMMMMm-  +h-oomhdMMMMMM+          ```              '),nl, 
    write('                                           :/-sM/` .yo .--`+MMMMsymMm+                         '),nl, 
    write('                                        `.+.` +-   `/`      /y-No  -sNN+`          `-::`       '),nl, 
    write('                                     `:++:.               .ooo.:s:    :yms:.```-+oo/.``+       '),nl, 
    write('                                   --:y/`    ```                   ```  `:+osso/.     .        '),nl, 
    write('                  .:` :.        `.+o/-       ```                   ```                         '),nl, 
    write('              `///:dmmNMMms..:hh+/:-                                                           '),nl, 
    write('         ``````......-/+ymNMMMMMh-                                                             '),nl, 
    write('                      .:/+.+mMMMN-                                                             '),nl, 
    write('           ```         `..---:hMMN-                                                            '),nl, 
    write('           ```  `   -s`      .--dM:`                                                           '),nl, 
    write('            `-/ymm+.yd`  `     ..+ms                                                           '),nl, 
    write('               /NMMNo-  .s      `--y.                                                          '),nl, 
    write('              .mMMd`   .:         .                                                            '),nl, 
    write('           :sdMMMMMy.oho           .                                                     ``.   '),nl, 
    write('         +NMMMMMMMMdss:                                                                  ```   '),nl, 
    write('      `oNMMMMMMMNmd.--                                                                         '),nl, 
    write('     .+yMMMMMMMMdhNh:                                                                          '),nl, 
    write('      +s+ydNMMMMMMMMy                                                                          '),nl, 
    write('     `   :NMNMMMMMMMM/           `..`                          .``.``.``.                      '),nl, 
    write('         `-sdMMMNMMMMd            ``                ``` `` `  `` ```    `` `` ``` `` ``        '),nl, 
    write('            -N.  `-/hh`                          ``````````````````````````````````````        '),nl, 
    write('            :/      -+/                           ` ``   `` ` `````  ` ` `` ``                 '),nl, 
    write('                                                                                               '),nl, 
    write('..`                                         `..`                   ..`                         '),nl.